Repository dnd-side-project/dnd-12th-7-backend, pull requests merged in 2025-03, with the labels that each got.

#101 저장된 이미지와 코드의 이미지명 통합
  src/main/java/com/dnd/moddo/domain/image/dto/CharacterResponse.java
  src/main/java/com/dnd/moddo/domain/image/entity/type/Characters.java
  src/test/java/com/dnd/moddo/domain/image/entity/type/CharacterTest.java
Labels: chore, 🛠️BE

#102 character 패키지 domain으로 이동
  src/main/java/com/dnd/moddo/domain/character/controller/CharacterController.java
  src/main/java/com/dnd/moddo/domain/character/entity/Character.java
  src/main/java/com/dnd/moddo/domain/character/repository/CharacterRepository.java
  src/main/java/com/dnd/moddo/domain/character/service/QueryCharacterService.java
  src/main/java/com/dnd/moddo/domain/character/service/implementation/CharacterReader.java
  src/main/java/com/dnd/moddo/domain/group/service/implementation/GroupCreator.java
  src/main/java/com/dnd/moddo/domain/image/dto/CharacterResponse.java
  src/test/java/com/dnd/moddo/domain/character/entity/CharacterTest.java
  src/test/java/com/dnd/moddo/domain/character/service/QueryCharacterServiceTest.java
  src/test/java/com/dnd/moddo/domain/character/service/implementation/CharacterReaderTest.java
  src/test/java/com/dnd/moddo/domain/group/service/implementation/GroupCreatorTest.java
Labels: chore

#104 도커 이미지 최적화
  .dockerignore
  .github/workflows/cicd.yml
  Dockerfile
Labels: 🛠️ Refactor, 🌐 Infra, 🛠️BE

#107 입금 내역 업데이트 시 낙관적 락 적용
  src/main/java/com/dnd/moddo/domain/groupMember/entity/GroupMember.java
  src/main/java/com/dnd/moddo/domain/groupMember/exception/PaymentConcurrencyException.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberUpdater.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/PaymentConcurrencyTest.java
Labels: chore, 🛠️BE
