Repository dnd-side-project/dnd-12th-7-backend, pull requests merged in 2025-02, with the labels that each got.

#23 비회원 사용자 생성
  build.gradle
  src/main/java/com/dnd/moddo/ModdoApplication.java
  src/main/java/com/dnd/moddo/domain/auth/controller/AuthController.java
  src/main/java/com/dnd/moddo/domain/auth/service/AuthService.java
  src/main/java/com/dnd/moddo/domain/user/entity/User.java
  src/main/java/com/dnd/moddo/domain/user/entity/type/Authority.java
  src/main/java/com/dnd/moddo/domain/user/exception/UserNotFoundException.java
  src/main/java/com/dnd/moddo/domain/user/repository/UserRepository.java
  src/main/java/com/dnd/moddo/global/config/PropertiesConfig.java
  src/main/java/com/dnd/moddo/global/jwt/auth/JwtAuth.java
  src/main/java/com/dnd/moddo/global/jwt/auth/JwtFilter.java
  src/main/java/com/dnd/moddo/global/jwt/dto/RefreshResponse.java
  src/main/java/com/dnd/moddo/global/jwt/dto/TokenResponse.java
  src/main/java/com/dnd/moddo/global/jwt/exception/MissingTokenException.java
  src/main/java/com/dnd/moddo/global/jwt/exception/TokenInvalidException.java
  src/main/java/com/dnd/moddo/global/jwt/properties/JwtConstants.java
  src/main/java/com/dnd/moddo/global/jwt/properties/JwtProperties.java
  src/main/java/com/dnd/moddo/global/jwt/utill/JwtProvider.java
  src/main/java/com/dnd/moddo/global/jwt/utill/JwtUtil.java
  src/main/java/com/dnd/moddo/global/security/SecurityConfig.java
  src/main/java/com/dnd/moddo/global/security/auth/AuthDetails.java
  src/main/java/com/dnd/moddo/global/security/auth/AuthDetailsService.java
  src/main/resources/application.yml
  src/test/java/com/dnd/moddo/domain/user/entity/UserTest.java
  src/test/resources/application.yml
Labels: ✨ Feature

#25 RefreshToken을 사용한 AccessToken 재발급 API 생성
  src/main/java/com/dnd/moddo/domain/auth/controller/AuthController.java
  src/main/java/com/dnd/moddo/domain/auth/exception/TokenInvalidException.java
  src/main/java/com/dnd/moddo/domain/auth/service/AuthService.java
  src/main/java/com/dnd/moddo/domain/auth/service/RefreshTokenService.java
  src/main/java/com/dnd/moddo/global/jwt/auth/JwtAuth.java
  src/main/java/com/dnd/moddo/global/jwt/dto/TokenResponse.java
  src/main/java/com/dnd/moddo/global/jwt/properties/JwtConstants.java
  src/main/java/com/dnd/moddo/global/jwt/utill/JwtProvider.java
  src/main/java/com/dnd/moddo/global/jwt/utill/JwtUtil.java
  src/main/java/com/dnd/moddo/global/security/auth/AuthDetailsService.java
  src/test/java/com/dnd/moddo/domain/auth/service/RefreshTokenServiceTest.java
Labels: ✨ Feature, 🛠️BE

#26 모임 생성 API
  src/main/java/com/dnd/moddo/domain/group/controller/GroupController.java
  src/main/java/com/dnd/moddo/domain/group/dto/GroupRequest.java
  src/main/java/com/dnd/moddo/domain/group/dto/GroupResponse.java
  src/main/java/com/dnd/moddo/domain/group/entity/Group.java
  src/main/java/com/dnd/moddo/domain/group/repository/GroupRepository.java
  src/main/java/com/dnd/moddo/domain/group/service/CommandGroupService.java
  src/main/java/com/dnd/moddo/domain/group/service/implementation/GroupCreater.java
  src/main/java/com/dnd/moddo/domain/user/exception/UserNotFoundException.java
  src/main/java/com/dnd/moddo/global/jwt/auth/JwtAuth.java
  src/main/java/com/dnd/moddo/global/jwt/auth/JwtFilter.java
  src/main/java/com/dnd/moddo/global/jwt/service/JwtService.java
  src/test/java/com/dnd/moddo/domain/group/entity/GroupTest.java
  src/test/java/com/dnd/moddo/domain/group/service/CommandGroupServiceTest.java
Labels: ✨ Feature, 🛠️BE

#27 지출 내역에 대한 기본 기능 추가
  src/main/java/com/dnd/moddo/domain/expense/controller/ExpenseController.java
  src/main/java/com/dnd/moddo/domain/expense/dto/request/ExpenseRequest.java
  src/main/java/com/dnd/moddo/domain/expense/dto/request/ExpensesRequest.java
  src/main/java/com/dnd/moddo/domain/expense/dto/response/ExpenseResponse.java
  src/main/java/com/dnd/moddo/domain/expense/dto/response/ExpensesResponse.java
  src/main/java/com/dnd/moddo/domain/expense/entity/Expense.java
  src/main/java/com/dnd/moddo/domain/expense/exception/ExpenseNotFoundException.java
  src/main/java/com/dnd/moddo/domain/expense/repository/ExpenseRepository.java
  src/main/java/com/dnd/moddo/domain/expense/service/CommandExpenseService.java
  src/main/java/com/dnd/moddo/domain/expense/service/QueryExpenseService.java
  src/main/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseCreator.java
  src/main/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseDeleter.java
  src/main/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseReader.java
  src/main/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseUpdater.java
  src/main/java/com/dnd/moddo/domain/groupMember/controller/GroupMemberController.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/CommandGroupMemberService.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberUpdater.java
  src/main/java/com/dnd/moddo/domain/memberExpense/dto/request/MemberExpenseRequest.java
  src/test/java/com/dnd/moddo/domain/expense/entity/ExpenseTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/CommandExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/QueryExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseCreatorTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseDeleterTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseReaderTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseUpdaterTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/entity/GroupMemberTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/CommandGroupMemberServiceTest.java
Labels: ✨ Feature, 🛠️BE

#30 계좌 추가 기능
  src/main/java/com/dnd/moddo/domain/group/controller/GroupController.java
  src/main/java/com/dnd/moddo/domain/group/dto/request/GroupAccountRequest.java
  src/main/java/com/dnd/moddo/domain/group/dto/request/GroupRequest.java
  src/main/java/com/dnd/moddo/domain/group/dto/response/GroupResponse.java
  src/main/java/com/dnd/moddo/domain/group/entity/Group.java
  src/main/java/com/dnd/moddo/domain/group/exception/GroupNotFoundException.java
  src/main/java/com/dnd/moddo/domain/group/repository/GroupRepository.java
  src/main/java/com/dnd/moddo/domain/group/service/CommandGroupService.java
  src/main/java/com/dnd/moddo/domain/group/service/implementation/GroupCreator.java
  src/main/java/com/dnd/moddo/domain/group/service/implementation/GroupUpdater.java
  src/test/java/com/dnd/moddo/domain/group/service/CommandGroupServiceTest.java
  src/test/java/com/dnd/moddo/domain/group/service/implementation/GroupCreatorTest.java
  src/test/java/com/dnd/moddo/domain/group/service/implementation/GroupUpdaterTest.java
Labels: ✨ Feature, 🛠️BE

#42 참여자 역할 추가 및 유효성 검사 추가
  src/main/java/com/dnd/moddo/domain/groupMember/controller/GroupMemberController.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/request/GroupMemberSaveRequest.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/request/GroupMembersSaveRequest.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/response/GroupMemberResponse.java
  src/main/java/com/dnd/moddo/domain/groupMember/entity/GroupMember.java
  src/main/java/com/dnd/moddo/domain/groupMember/entity/type/ExpenseRole.java
  src/main/java/com/dnd/moddo/domain/groupMember/exception/ExpenseRoleNotFoundException.java
  src/main/java/com/dnd/moddo/domain/groupMember/exception/InvalidExpenseParticipantsException.java
  src/main/java/com/dnd/moddo/domain/groupMember/exception/ManagerCannotDeleteException.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/CommandGroupMemberService.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreator.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberDeleter.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberUpdater.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberValidator.java
  src/main/java/com/dnd/moddo/domain/memberExpense/dto/response/MemberExpenseResponse.java
  src/test/java/com/dnd/moddo/domain/expense/service/QueryExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/entity/GroupMemberTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/CommandGroupMemberServiceTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/QueryGroupMemberServiceTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreatorTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberDeleterTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberReaderTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberUpdaterTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberValidatorTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/QueryMemberExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/implementation/MemberExpenseCreatorTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/implementation/MemberExpenseReaderTest.java
Labels: ✨ Feature, 🛠️BE

#46 지출 내역 순서 변경에 대한 기능 추가
  src/main/java/com/dnd/moddo/domain/expense/controller/ExpenseController.java
  src/main/java/com/dnd/moddo/domain/expense/dto/request/ExpensesUpdateOrderRequest.java
  src/main/java/com/dnd/moddo/domain/expense/service/CommandExpenseService.java
  src/main/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseUpdater.java
  src/test/java/com/dnd/moddo/domain/expense/service/CommandExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseUpdaterTest.java
Labels: ✨ Feature, 🛠️BE

#50 기존 모임 Id 토큰으로 변경
  src/main/java/com/dnd/moddo/domain/expense/controller/ExpenseController.java
  src/main/java/com/dnd/moddo/domain/groupMember/controller/GroupMemberController.java
  src/main/java/com/dnd/moddo/global/jwt/utill/JwtProvider.java
Labels: chore, 🛠️BE

#51 테스트를 위한 2차 배포
  src/main/java/com/dnd/moddo/domain/expense/controller/ExpenseController.java
  src/main/java/com/dnd/moddo/domain/expense/dto/request/ExpensesUpdateOrderRequest.java
  src/main/java/com/dnd/moddo/domain/expense/service/CommandExpenseService.java
  src/main/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseUpdater.java
  src/main/java/com/dnd/moddo/domain/group/controller/GroupController.java
  src/main/java/com/dnd/moddo/domain/group/entity/Group.java
  src/main/java/com/dnd/moddo/domain/group/exception/GroupNotAuthorException.java
  src/main/java/com/dnd/moddo/domain/group/service/CommandGroupService.java
  src/main/java/com/dnd/moddo/domain/group/service/implementation/GroupCreator.java
  src/main/java/com/dnd/moddo/domain/group/service/implementation/GroupReader.java
  src/main/java/com/dnd/moddo/domain/group/service/implementation/GroupValidator.java
  src/main/java/com/dnd/moddo/domain/groupMember/controller/GroupMemberController.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/request/GroupMemberSaveRequest.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/request/GroupMembersSaveRequest.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/response/GroupMemberResponse.java
  src/main/java/com/dnd/moddo/domain/groupMember/entity/GroupMember.java
  src/main/java/com/dnd/moddo/domain/groupMember/entity/type/ExpenseRole.java
  src/main/java/com/dnd/moddo/domain/groupMember/exception/ExpenseRoleNotFoundException.java
  src/main/java/com/dnd/moddo/domain/groupMember/exception/InvalidExpenseParticipantsException.java
  src/main/java/com/dnd/moddo/domain/groupMember/exception/ManagerCannotDeleteException.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/CommandGroupMemberService.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreator.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberDeleter.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberUpdater.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberValidator.java
  src/main/java/com/dnd/moddo/domain/memberExpense/dto/response/MemberExpenseResponse.java
  src/main/java/com/dnd/moddo/global/jwt/dto/GroupTokenResponse.java
  src/main/java/com/dnd/moddo/global/jwt/properties/JwtConstants.java
  src/main/java/com/dnd/moddo/global/jwt/service/JwtService.java
  src/main/java/com/dnd/moddo/global/jwt/utill/JwtProvider.java
  src/main/java/com/dnd/moddo/global/jwt/utill/JwtUtil.java
  src/test/java/com/dnd/moddo/domain/expense/service/CommandExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/QueryExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseUpdaterTest.java
  src/test/java/com/dnd/moddo/domain/group/service/CommandGroupServiceTest.java
  src/test/java/com/dnd/moddo/domain/group/service/implementation/GroupCreatorTest.java
  src/test/java/com/dnd/moddo/domain/group/service/implementation/GroupReaderTest.java
  src/test/java/com/dnd/moddo/domain/group/service/implementation/GroupValidatorTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/entity/GroupMemberTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/CommandGroupMemberServiceTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/QueryGroupMemberServiceTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreatorTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberDeleterTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberReaderTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberUpdaterTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberValidatorTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/QueryMemberExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/implementation/MemberExpenseCreatorTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/implementation/MemberExpenseReaderTest.java
Labels: 🌐 Infra, 🛠️BE

#55 단건 모임 조회 기능
  build.gradle
  src/main/java/com/dnd/moddo/domain/group/controller/GroupController.java
  src/main/java/com/dnd/moddo/domain/group/dto/response/GroupDetailResponse.java
  src/main/java/com/dnd/moddo/domain/group/repository/GroupRepository.java
  src/main/java/com/dnd/moddo/domain/group/service/QueryGroupService.java
  src/main/java/com/dnd/moddo/domain/group/service/implementation/GroupReader.java
  src/test/java/com/dnd/moddo/domain/group/service/QueryGroupServiceTest.java
  src/test/java/com/dnd/moddo/domain/group/service/implementation/GroupReaderTest.java
Labels: ✨ Feature, 🛠️BE

#59 전체 지출내역 조회 기능 추가
  src/main/java/com/dnd/moddo/domain/expense/controller/ExpenseController.java
  src/main/java/com/dnd/moddo/domain/expense/dto/response/ExpenseDetailResponse.java
  src/main/java/com/dnd/moddo/domain/expense/dto/response/ExpenseDetailsResponse.java
  src/main/java/com/dnd/moddo/domain/expense/service/CommandExpenseService.java
  src/main/java/com/dnd/moddo/domain/expense/service/QueryExpenseService.java
  src/main/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseDeleter.java
  src/main/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseReader.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/response/GroupMemberExpenseResponse.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/QueryGroupMemberService.java
  src/main/java/com/dnd/moddo/domain/memberExpense/repotiroy/MemberExpenseRepository.java
  src/main/java/com/dnd/moddo/domain/memberExpense/service/CommandMemberExpenseService.java
  src/main/java/com/dnd/moddo/domain/memberExpense/service/QueryMemberExpenseService.java
  src/main/java/com/dnd/moddo/domain/memberExpense/service/implementation/MemberExpenseReader.java
  src/test/java/com/dnd/moddo/domain/expense/service/CommandExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/QueryExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseDeleterTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseReaderTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/CommandMemberExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/QueryMemberExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/implementation/MemberExpenseReaderTest.java
Labels: ✨ Feature, 🛠️ Refactor, 🛠️BE

#61 백엔드에서 총무(정산담당자)생성하도록 로직 수정
  src/main/java/com/dnd/moddo/domain/groupMember/controller/GroupMemberController.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/request/GroupMemberSaveRequest.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/request/GroupMembersSaveRequest.java
  src/main/java/com/dnd/moddo/domain/groupMember/entity/GroupMember.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/CommandGroupMemberService.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreator.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberValidator.java
  src/main/java/com/dnd/moddo/domain/memberExpense/service/QueryMemberExpenseService.java
  src/test/java/com/dnd/moddo/domain/group/service/QueryGroupServiceTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/CommandGroupMemberServiceTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreatorTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberValidatorTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/QueryMemberExpenseServiceTest.java
Labels: ✨ Feature, chore, 🛠️BE

#63 지출 내역 생성, 참여자 추가, 참여자별 지출 내역 생성에 대한 입력값 검증 추가
  src/main/java/com/dnd/moddo/domain/expense/controller/ExpenseController.java
  src/main/java/com/dnd/moddo/domain/expense/dto/request/ExpenseRequest.java
  src/main/java/com/dnd/moddo/domain/expense/dto/request/ExpensesRequest.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/request/GroupMemberSaveRequest.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreator.java
  src/main/java/com/dnd/moddo/domain/memberExpense/dto/request/MemberExpenseRequest.java
  src/main/java/com/dnd/moddo/domain/memberExpense/service/QueryMemberExpenseService.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreatorTest.java
Labels: 🛠️ Refactor, chore, 🛠️BE

#69 비회원 비밀번호 검증 기능
  src/main/java/com/dnd/moddo/domain/group/controller/GroupController.java
  src/main/java/com/dnd/moddo/domain/group/dto/request/GroupPasswordRequest.java
  src/main/java/com/dnd/moddo/domain/group/dto/response/GroupPasswordResponse.java
  src/main/java/com/dnd/moddo/domain/group/exception/InvalidPasswordException.java
  src/main/java/com/dnd/moddo/domain/group/service/CommandGroupService.java
  src/main/java/com/dnd/moddo/domain/group/service/QueryGroupService.java
  src/main/java/com/dnd/moddo/domain/group/service/implementation/GroupValidator.java
  src/test/java/com/dnd/moddo/domain/group/service/CommandGroupServiceTest.java
  src/test/java/com/dnd/moddo/domain/group/service/QueryGroupServiceTest.java
  src/test/java/com/dnd/moddo/domain/group/service/implementation/GroupValidatorTest.java
Labels: ✨ Feature, 🛠️BE

#71 aop를 활용하여 사용자 검증하는 기능 추가
  src/main/java/com/dnd/moddo/domain/auth/exception/TokenNotFoundException.java
  src/main/java/com/dnd/moddo/domain/auth/exception/UserPermissionException.java
  src/main/java/com/dnd/moddo/domain/expense/controller/ExpenseController.java
  src/main/java/com/dnd/moddo/domain/groupMember/controller/GroupMemberController.java
  src/main/java/com/dnd/moddo/global/common/annotation/VerifyManagerPermission.java
  src/main/java/com/dnd/moddo/global/common/aop/GroupPermissionAspect.java
Labels: ✨ Feature, 🛠️BE

#72 캐릭터 확률에 따른 랜덤 배정
  src/main/java/com/dnd/moddo/domain/image/controller/ImageController.java
  src/main/java/com/dnd/moddo/domain/image/dto/CharacterResponse.java
  src/main/java/com/dnd/moddo/domain/image/entity/type/Character.java
  src/main/java/com/dnd/moddo/domain/image/exception/CharacterNotFoundException.java
  src/main/java/com/dnd/moddo/domain/image/service/QueryImageService.java
  src/main/java/com/dnd/moddo/domain/image/service/implementation/ImageReader.java
  src/test/java/com/dnd/moddo/domain/image/entity/type/CharacterTest.java
  src/test/java/com/dnd/moddo/domain/image/service/QueryImageServiceTest.java
  src/test/java/com/dnd/moddo/domain/image/service/implementation/ImageReaderTest.java
Labels: ✨ Feature, 🛠️BE

#73 모임 지출내역 상단 기능
  src/main/java/com/dnd/moddo/domain/expense/repository/ExpenseRepository.java
  src/main/java/com/dnd/moddo/domain/group/controller/GroupController.java
  src/main/java/com/dnd/moddo/domain/group/dto/response/GroupHeaderResponse.java
  src/main/java/com/dnd/moddo/domain/group/entity/Group.java
  src/main/java/com/dnd/moddo/domain/group/service/QueryGroupService.java
  src/main/java/com/dnd/moddo/domain/group/service/implementation/GroupReader.java
  src/main/java/com/dnd/moddo/global/security/SecurityConfig.java
  src/test/java/com/dnd/moddo/domain/expense/entity/ExpenseTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/CommandExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/QueryExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseCreatorTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseReaderTest.java
  src/test/java/com/dnd/moddo/domain/group/entity/GroupTest.java
  src/test/java/com/dnd/moddo/domain/group/service/QueryGroupServiceTest.java
  src/test/java/com/dnd/moddo/domain/group/service/implementation/GroupCreatorTest.java
  src/test/java/com/dnd/moddo/domain/group/service/implementation/GroupReaderTest.java
  src/test/java/com/dnd/moddo/domain/group/service/implementation/GroupValidatorTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/entity/GroupMemberTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/CommandGroupMemberServiceTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/QueryGroupMemberServiceTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreatorTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberDeleterTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberReaderTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberUpdaterTest.java
  src/test/java/com/dnd/moddo/domain/image/service/implementation/ImageReaderTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/QueryMemberExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/implementation/MemberExpenseCreatorTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/implementation/MemberExpenseReaderTest.java
Labels: ✨ Feature, 🛠️BE

#77 hotfix: cors 설정 추가
  src/main/java/com/dnd/moddo/global/config/WebConfig.java
  src/main/java/com/dnd/moddo/global/security/SecurityConfig.java
Labels: 🐞 Bug

#79 모임 생성 후 총무 자동 생성 기능 추가
  src/main/java/com/dnd/moddo/domain/group/controller/GroupController.java
  src/main/java/com/dnd/moddo/domain/group/dto/response/GroupSaveResponse.java
  src/main/java/com/dnd/moddo/domain/group/service/CommandGroupService.java
  src/main/java/com/dnd/moddo/domain/group/service/implementation/GroupCreator.java
  src/main/java/com/dnd/moddo/domain/groupMember/controller/GroupMemberController.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/request/GroupMemberSaveRequest.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/response/GroupMemberExpenseResponse.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/response/GroupMemberResponse.java
  src/main/java/com/dnd/moddo/domain/groupMember/entity/GroupMember.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/CommandGroupMemberService.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreator.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberUpdater.java
  src/main/java/com/dnd/moddo/domain/memberExpense/dto/request/MemberExpenseRequest.java
  src/main/java/com/dnd/moddo/domain/memberExpense/dto/response/MemberExpenseResponse.java
  src/main/java/com/dnd/moddo/domain/memberExpense/service/CommandMemberExpenseService.java
  src/main/java/com/dnd/moddo/domain/memberExpense/service/implementation/MemberExpenseValidator.java
  src/main/java/com/dnd/moddo/global/jwt/utill/JwtProvider.java
  src/test/java/com/dnd/moddo/domain/expense/service/QueryExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/group/service/CommandGroupServiceTest.java
  src/test/java/com/dnd/moddo/domain/group/service/implementation/GroupCreatorTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/CommandGroupMemberServiceTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreatorTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberUpdaterTest.java
Labels: ✨ Feature, 🛠️BE

#80 Release v0.0.5
  src/main/java/com/dnd/moddo/domain/group/controller/GroupController.java
  src/main/java/com/dnd/moddo/domain/group/dto/response/GroupSaveResponse.java
  src/main/java/com/dnd/moddo/domain/group/service/CommandGroupService.java
  src/main/java/com/dnd/moddo/domain/group/service/implementation/GroupCreator.java
  src/main/java/com/dnd/moddo/domain/groupMember/controller/GroupMemberController.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/request/GroupMemberSaveRequest.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/response/GroupMemberExpenseResponse.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/response/GroupMemberResponse.java
  src/main/java/com/dnd/moddo/domain/groupMember/entity/GroupMember.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/CommandGroupMemberService.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreator.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberUpdater.java
  src/main/java/com/dnd/moddo/domain/memberExpense/dto/request/MemberExpenseRequest.java
  src/main/java/com/dnd/moddo/domain/memberExpense/dto/response/MemberExpenseResponse.java
  src/main/java/com/dnd/moddo/domain/memberExpense/service/CommandMemberExpenseService.java
  src/main/java/com/dnd/moddo/domain/memberExpense/service/implementation/MemberExpenseValidator.java
  src/main/java/com/dnd/moddo/global/jwt/utill/JwtProvider.java
  src/test/java/com/dnd/moddo/domain/expense/service/QueryExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/group/service/CommandGroupServiceTest.java
  src/test/java/com/dnd/moddo/domain/group/service/implementation/GroupCreatorTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/CommandGroupMemberServiceTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreatorTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberUpdaterTest.java
Labels: 🛠️BE, release

#81 참여자 추가 시 프로필 자동 할당 기능
  src/main/java/com/dnd/moddo/domain/group/controller/GroupController.java
  src/main/java/com/dnd/moddo/domain/group/dto/response/GroupResponse.java
  src/main/java/com/dnd/moddo/domain/group/entity/Group.java
  src/main/java/com/dnd/moddo/domain/group/service/implementation/GroupCreator.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/request/GroupMemberSaveRequest.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/request/GroupMembersSaveRequest.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/response/GroupMemberExpenseResponse.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/response/GroupMemberResponse.java
  src/main/java/com/dnd/moddo/domain/groupMember/entity/GroupMember.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreator.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberUpdater.java
  src/main/java/com/dnd/moddo/domain/image/controller/ImageController.java
  src/main/java/com/dnd/moddo/domain/image/dto/CharacterResponse.java
  src/main/java/com/dnd/moddo/domain/image/service/QueryImageService.java
  src/main/java/com/dnd/moddo/domain/image/service/implementation/ImageReader.java
  src/main/java/com/dnd/moddo/domain/memberExpense/dto/response/MemberExpenseResponse.java
  src/test/java/com/dnd/moddo/domain/expense/entity/ExpenseTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/CommandExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/QueryExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseCreatorTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseReaderTest.java
  src/test/java/com/dnd/moddo/domain/group/entity/GroupTest.java
  src/test/java/com/dnd/moddo/domain/group/service/CommandGroupServiceTest.java
  src/test/java/com/dnd/moddo/domain/group/service/QueryGroupServiceTest.java
  src/test/java/com/dnd/moddo/domain/group/service/implementation/GroupCreatorTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/entity/GroupMemberTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/CommandGroupMemberServiceTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/QueryGroupMemberServiceTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreatorTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberDeleterTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberReaderTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberUpdaterTest.java
  src/test/java/com/dnd/moddo/domain/image/service/QueryImageServiceTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/QueryMemberExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/implementation/MemberExpenseCreatorTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/implementation/MemberExpenseReaderTest.java
Labels: chore, 🛠️BE

#84 프로필 자동 할당 profileId에 따라 변경
  src/main/java/com/dnd/moddo/domain/groupMember/dto/request/GroupMemberSaveRequest.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/response/GroupMemberExpenseResponse.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/response/GroupMemberResponse.java
  src/main/java/com/dnd/moddo/domain/groupMember/entity/GroupMember.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreator.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberUpdater.java
  src/main/java/com/dnd/moddo/domain/memberExpense/dto/response/MemberExpenseResponse.java
  src/test/java/com/dnd/moddo/domain/group/service/QueryGroupServiceTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/entity/GroupMemberTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/CommandGroupMemberServiceTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/QueryGroupMemberServiceTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreatorTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberDeleterTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberReaderTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberUpdaterTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/QueryMemberExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/implementation/MemberExpenseCreatorTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/implementation/MemberExpenseReaderTest.java
Labels: chore, 🛠️BE

#86 모니터링을 위한 의존성 설정
  build.gradle
Labels: ⚙️ Setting, 🌐 Infra, 🛠️BE

#88 Release v0.0.6
  build.gradle
  src/main/java/com/dnd/moddo/domain/group/controller/GroupController.java
  src/main/java/com/dnd/moddo/domain/group/dto/response/GroupResponse.java
  src/main/java/com/dnd/moddo/domain/group/entity/Group.java
  src/main/java/com/dnd/moddo/domain/group/service/implementation/GroupCreator.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/request/GroupMemberSaveRequest.java
  src/main/java/com/dnd/moddo/domain/groupMember/dto/request/GroupMembersSaveRequest.java
  src/main/java/com/dnd/moddo/domain/groupMember/entity/GroupMember.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreator.java
  src/main/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberUpdater.java
  src/main/java/com/dnd/moddo/domain/image/controller/ImageController.java
  src/main/java/com/dnd/moddo/domain/image/dto/CharacterResponse.java
  src/main/java/com/dnd/moddo/domain/image/service/QueryImageService.java
  src/main/java/com/dnd/moddo/domain/image/service/implementation/ImageReader.java
  src/test/java/com/dnd/moddo/domain/expense/entity/ExpenseTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/CommandExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/QueryExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseCreatorTest.java
  src/test/java/com/dnd/moddo/domain/expense/service/implementation/ExpenseReaderTest.java
  src/test/java/com/dnd/moddo/domain/group/entity/GroupTest.java
  src/test/java/com/dnd/moddo/domain/group/service/CommandGroupServiceTest.java
  src/test/java/com/dnd/moddo/domain/group/service/QueryGroupServiceTest.java
  src/test/java/com/dnd/moddo/domain/group/service/implementation/GroupCreatorTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/entity/GroupMemberTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/CommandGroupMemberServiceTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/QueryGroupMemberServiceTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberCreatorTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberDeleterTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberReaderTest.java
  src/test/java/com/dnd/moddo/domain/groupMember/service/implementation/GroupMemberUpdaterTest.java
  src/test/java/com/dnd/moddo/domain/image/service/QueryImageServiceTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/QueryMemberExpenseServiceTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/implementation/MemberExpenseCreatorTest.java
  src/test/java/com/dnd/moddo/domain/memberExpense/service/implementation/MemberExpenseReaderTest.java
Labels: 🛠️BE, release

#89 fix: prometheus 설정 누락된 부분 추가
  src/main/resources/application.yml
Labels: 🐞 Bug, 🛠️BE

#91 모임 생성시 랜덤 캐릭터 할당
  src/main/java/com/dnd/moddo/character/controller/CharacterController.java
  src/main/java/com/dnd/moddo/character/entity/Character.java
  src/main/java/com/dnd/moddo/character/repository/CharacterRepository.java
  src/main/java/com/dnd/moddo/character/service/QueryCharacterService.java
  src/main/java/com/dnd/moddo/character/service/implementation/CharacterReader.java
  src/main/java/com/dnd/moddo/domain/group/service/implementation/GroupCreator.java
  src/main/java/com/dnd/moddo/domain/image/controller/ImageController.java
  src/main/java/com/dnd/moddo/domain/image/dto/CharacterResponse.java
  src/main/java/com/dnd/moddo/domain/image/entity/type/Character.java
  src/main/java/com/dnd/moddo/domain/image/entity/type/Characters.java
  src/main/java/com/dnd/moddo/domain/image/exception/CharacterNotFoundException.java
  src/main/java/com/dnd/moddo/domain/image/service/QueryImageService.java
  src/main/java/com/dnd/moddo/domain/image/service/implementation/ImageReader.java
  src/test/java/com/dnd/moddo/domain/character/entity/CharacterTest.java
  src/test/java/com/dnd/moddo/domain/character/service/QueryCharacterServiceTest.java
  src/test/java/com/dnd/moddo/domain/character/service/implementation/CharacterReaderTest.java
  src/test/java/com/dnd/moddo/domain/group/service/implementation/GroupCreatorTest.java
  src/test/java/com/dnd/moddo/domain/image/entity/type/CharacterTest.java
  src/test/java/com/dnd/moddo/domain/image/service/QueryImageServiceTest.java
  src/test/java/com/dnd/moddo/domain/image/service/implementation/ImageReaderTest.java
Labels: ✨ Feature, chore, 🛠️BE

#99 캐락터 url hotfix 반영
  src/main/java/com/dnd/moddo/domain/image/dto/CharacterResponse.java
  src/main/java/com/dnd/moddo/domain/image/entity/type/Characters.java
Labels: 🐞 Bug, 🛠️BE
